# Generated by Django 4.1.1 on 2022-09-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ciclo', models.IntegerField(verbose_name='Ciclos')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('horas', models.FloatField(max_length=5, verbose_name='Horas')),
                ('creditos', models.IntegerField(verbose_name='Creditos')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedatos.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('id_curso', models.ManyToManyField(to='basedatos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='JefeDepartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('id_departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basedatos.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedatos.departamento'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('id_curso', models.ManyToManyField(to='basedatos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('ciclo', models.IntegerField(verbose_name='Ciclo')),
                ('id_curso', models.ManyToManyField(to='basedatos.curso')),
            ],
        ),
    ]
